In [1]:
import pandas as pd
updown_path = "./toden/toden_counts_updown_genes.csv"
toden_counts = pd.read_csv(updown_path)

In [21]:
print(toden_counts)

               index  SRR10192321  SRR10192320  SRR10192319  SRR10192318  \
0    ENSG00000078369         3579         4036         3483         4901
1    ENSG00000130939          920          753         1037          384
2    ENSG00000162545           67           22           32            2
3    ENSG00000173372          202          333          145          138
4    ENSG00000004455          246          293          316          251
..               ...          ...          ...          ...          ...
274  ENSG00000182858            5           53           37           81
275  ENSG00000142192         1276         3400         3104         4840
276  ENSG00000156273         1298         2149         1889          835
277  ENSG00000159082          232          247          239           95
278  ENSG00000197381          679          652          609          770

     SRR10192317  SRR10192316  SRR10192315  SRR10192314  SRR10192313  ...  \
0           2491         3856         3363          772         1788  ...
1            620          891          717           97          466  ...
2             11            0           30            4            0  ...
3            153          386          188           82          318  ...
4            147          275          298           64          135  ...
..           ...          ...          ...          ...          ...  ...
274           17           19           53           17            7  ...
275         3567         2123         3088          392         1753  ...
276          897         1939         1194          231         1044  ...
277          183          161          345           57          144  ...
278          140          505          425          150          331  ...

     SRR10192332  SRR10192331  SRR10192330  SRR10192329  SRR10192328  \
0           2364          681         1626         1740          790
1            309          127          114          171          113
2              1            0            1            2           13
3             16           45           69           28            7
4            113           47           69           24           26
..           ...          ...          ...          ...          ...
274           11           14            0           14            7
275         2873          311         1353         1536          855
276         1090           48          509          172          140
277           41           51           67           67           83
278          334           10          265           81          135

     SRR10192327  SRR10192326  SRR10192325  SRR10192324  SRR10192322
0            916         1616          498          749          849
1            222          250           73          144          260
2              1            0            5            0            0
3             88           49            9            2            5
4             61           47           26           13           35
..           ...          ...          ...          ...          ...
274            2            0            5            0            2
275         1133         1490          607          859         1562
276          389          261           71           59          289
277          159           23           23            4           18
278          165           54           92          192          319

[279 rows x 335 columns]

In [2]:
burgos_path = r"C:\Users\danie\Documents\acid_log_scale_d\BENG203\AD_prediction_blood\burgos_dbgap\burgos_dbgap_counts.txt"
burgos_df = pd.read_csv(burgos_path, sep = '\t')

In [3]:
burgos_df['index'] = burgos_df.index

In [4]:
just_idx = toden_counts['index']

In [5]:
at_idx = burgos_df.merge(just_idx, on = ['index'])

In [6]:
at_idx.set_index('index')

,01_16_CSF,01_16_SER,01_18_CSF,01_18_SER,01_37_CSF,01_37_SER,01_44_CSF,01_44_SER,01_46_CSF,01_46_SER,...,99_48_CSF,99_48_SER,99_52_CSF,99_52_SER,99_58_CSF,99_58_SER,99_60_CSF,99_60_SER,99_64_CSF,99_64_SER
index,,,,,,,,,,,,,,,,,,,,,
ENSG00000078369,1,2,0,27,0,26,1,4,2,23,...,3,3,0,16,0,3,6,3,9,10
ENSG00000130939,9,3,0,32,0,7,2,11,4,3,...,3,4,4,7,4,1,2,5,8,35
ENSG00000162545,0,0,0,3,0,0,1,1,3,0,...,0,0,2,0,0,1,3,0,0,0
ENSG00000173372,0,0,0,21,0,2,1,2,0,228,...,0,2,2,5,0,3,2,0,0,2
ENSG00000004455,0,2,2,10,0,3,0,0,0,0,...,1,0,0,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG00000182858,0,0,0,1,1,1,0,0,0,0,...,0,0,0,3,2,0,0,0,0,0
ENSG00000142192,11,2,5,31,2,16,6,4,8,6,...,2,0,4,9,1,0,5,0,12,10
ENSG00000156273,4,0,0,1,0,4,0,0,3,5,...,0,0,0,24,0,0,1,0,0,1
ENSG00000159082,3,1,0,4,0,1,1,1,1,1,...,1,2,0,6,0,0,1,0,0,10
ENSG00000197381,0,0,1,7,0,2,0,2,3,2,...,1,0,3,0,0,0,4,0,0,0

In [17]:
column_to_move = at_idx.pop("index")
at_idx.insert(0, "index", column_to_move)

In [18]:
print(at_idx)

               index  01_16_CSF  01_16_SER  01_18_CSF  01_18_SER  01_37_CSF  \
0    ENSG00000078369          1          2          0         27          0
1    ENSG00000130939          9          3          0         32          0
2    ENSG00000162545          0          0          0          3          0
3    ENSG00000173372          0          0          0         21          0
4    ENSG00000004455          0          2          2         10          0
..               ...        ...        ...        ...        ...        ...
274  ENSG00000182858          0          0          0          1          1
275  ENSG00000142192         11          2          5         31          2
276  ENSG00000156273          4          0          0          1          0
277  ENSG00000159082          3          1          0          4          0
278  ENSG00000197381          0          0          1          7          0

     01_37_SER  01_44_CSF  01_44_SER  01_46_CSF  ...  99_48_CSF  99_48_SER  \
0           26          1          4          2  ...          3          3
1            7          2         11          4  ...          3          4
2            0          1          1          3  ...          0          0
3            2          1          2          0  ...          0          2
4            3          0          0          0  ...          1          0
..         ...        ...        ...        ...  ...        ...        ...
274          1          0          0          0  ...          0          0
275         16          6          4          8  ...          2          0
276          4          0          0          3  ...          0          0
277          1          1          1          1  ...          1          2
278          2          0          2          3  ...          1          0

     99_52_CSF  99_52_SER  99_58_CSF  99_58_SER  99_60_CSF  99_60_SER  \
0            0         16          0          3          6          3
1            4          7          4          1          2          5
2            2          0          0          1          3          0
3            2          5          0          3          2          0
4            0          1          0          0          1          0
..         ...        ...        ...        ...        ...        ...
274          0          3          2          0          0          0
275          4          9          1          0          5          0
276          0         24          0          0          1          0
277          0          6          0          0          1          0
278          3          0          0          0          4          0

     99_64_CSF  99_64_SER
0            9         10
1            8         35
2            0          0
3            0          2
4            0          0
..         ...        ...
274          0          0
275         12         10
276          0          1
277          0         10
278          0          0

[279 rows x 268 columns]

In [19]:
at_idx.to_csv(r"C:\Users\danie\Documents\acid_log_scale_d\BENG203\AD_prediction_blood\burgos_dbgap\burgos_dbgap_updown_genes.csv", index = False)

In [22]:
pd.read_csv(r"C:\Users\danie\Documents\acid_log_scale_d\BENG203\AD_prediction_blood\burgos_dbgap\burgos_dbgap_updown_genes.csv")

,index,01_16_CSF,01_16_SER,01_18_CSF,01_18_SER,01_37_CSF,01_37_SER,01_44_CSF,01_44_SER,01_46_CSF,...,99_48_CSF,99_48_SER,99_52_CSF,99_52_SER,99_58_CSF,99_58_SER,99_60_CSF,99_60_SER,99_64_CSF,99_64_SER
0,ENSG00000078369,1,2,0,27,0,26,1,4,2,...,3,3,0,16,0,3,6,3,9,10
1,ENSG00000130939,9,3,0,32,0,7,2,11,4,...,3,4,4,7,4,1,2,5,8,35
2,ENSG00000162545,0,0,0,3,0,0,1,1,3,...,0,0,2,0,0,1,3,0,0,0
3,ENSG00000173372,0,0,0,21,0,2,1,2,0,...,0,2,2,5,0,3,2,0,0,2
4,ENSG00000004455,0,2,2,10,0,3,0,0,0,...,1,0,0,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
274,ENSG00000182858,0,0,0,1,1,1,0,0,0,...,0,0,0,3,2,0,0,0,0,0
275,ENSG00000142192,11,2,5,31,2,16,6,4,8,...,2,0,4,9,1,0,5,0,12,10
276,ENSG00000156273,4,0,0,1,0,4,0,0,3,...,0,0,0,24,0,0,1,0,0,1
277,ENSG00000159082,3,1,0,4,0,1,1,1,1,...,1,2,0,6,0,0,1,0,0,10
278,ENSG00000197381,0,0,1,7,0,2,0,2,3,...,1,0,3,0,0,0,4,0,0,0